version: 0.0
os: linux

files:
  - source:  /
    destination: /home/ubuntu/app
    overwrite: yes

permissions:
  - object: /
    owner: ubuntu
    group: ubuntu

# https://docs.aws.amazon.com/ko_kr/codedeploy/latest/userguide/reference-appspec-file-structure-hooks.html  -> "인 플레이스(in-place) 배포"를 검색
hooks:
  ApplicationStop:
    - location: scripts/create-dir.sh
      timeout: 60
      runas: ubuntu
  BeforeInstall:
    - location: scripts/set-prod-env.sh
      timeout: 60
      runas: ubuntu
  AfterInstall:
    - location: scripts/stop.sh
      timeout: 60
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
      runas: ubuntu