spring:
  application:
    name: arbitrage
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:123456}
  datasource:
    url: ${PG_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${PG_USERNAME:postgres}
    password: ${PG_PASSWORD:5432}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 4
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false
    prefix: classpath:templates/
    suffix: .html
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_ID:mail-username}
    password: ${MAIL_PASSWORD:mail-pw}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:google-client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:google-client-secret}
            scope:
              - email
              - profile
          kakao:
            client-id: ${KAKAO_CLIENT_ID:kakao-client-id}
            client-secret: ${KAKAO_CLIENT_SECRET:kakao-client-secret}
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - account_email
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            user-name-attribute: id
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
server:
  port: ${SERVER_PORT:8000}

jwt:
  secret: ${JWT_SECRET:fhasdjkfhasdjkfhasdjkjfhdsajkfhskajdfhjksadhfkjsdahfjksadhfkjdsa}

mail:
  secret: ${MAIL_SECRET:fhasdjkfhasdjkfhasdjkjfhdsajkfhskajdfhjksadhfkjsdahfjksadhfkjdsa}

token:
  access: 1800000 # 30minutes
  refresh: 604800000 # 7days

ip-address: ${IP_ADDRESS:12.34.56.789}