spring:
  application:
    name: arbitrage
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
  datasource:
    url: ${PG_URL}
    username: ${PG_USERNAME:postgres}
    password: ${PG_PASSWORD:5432}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 4
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false
    prefix: classpath:templates/
    suffix: .html
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_ID}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
server:
  port: ${SERVER_PORT:8000}

jwt:
  secret: ${JWT_SECRET}

mail:
  secret: ${MAIL_SECRET}

token:
  access: 3600000 # 1hour
  refresh: 604800000 # 7days