spring:
  application:
    name: arbitrage
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 4
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: ${SERVER_PORT:8000}

jwt:
  secret: ${JWT_SECRET}

